name: sl2
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  # Python
  - python>=3.10
  - numpy
  - scipy

  # R
  - r-base=4.5.2

  # Bioconductor
  - bioconductor-deseq2
  - bioconductor-apeglm
  - bioconductor-limma

  # Core R packages requested
  - r-argparse
  - r-ggplot2
  - r-ggrepel
  - r-reshape
  - r-ggridges
  - r-amap
  - r-gridextra
  - r-gtable
  - r-igraph
  - r-network
  - r-ggally
  - r-ggwordcloud
  - r-dplyr
  - r-shiny
  - r-fs

  # Additional R packages not specified (I think)
  - r-ggplotify
  - r-ggfittext
  - r-sna

  # Helpers to install any missing CRAN packages from inside R
  - r-remotes
  - r-devtools

  # Optional: pip (kept available if needed later)
  - pip